[package]
# ::TODO rename this crate to <something>_compiler::
name = "compiler"

version = "0.0.0"
license = "MIT"

edition = "2021"

[dependencies]
# Local crates
brr.workspace = true

# External crates
serde.workspace = true
serde_json.workspace = true
relative-path.workspace = true

