[package]
name = "compiler"

license = "MIT"

edition = "2021"

version = "0.0.0"
publish = false


[features]
default = []
mml_tracking = []


[dependencies]
# Local crates
brr.workspace = true

# External crates
serde.workspace = true
serde_json.workspace = true
relative-path.workspace = true

