[workspace]
resolver = "2"

members = [
    "crates/brr",
    "crates/compiler",
    "crates/shvc-sound-emu",

    "crates/tad-compiler",
    "crates/tad-gui",
    "crates/wav2brr",
]


# Reduce the size of the release binaries
[profile.release]
strip = true
opt-level = "z"
# Must use false here.
# Enabling lto crashes on Windows when opening a Save As dialog.
# (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
lto = false


[workspace.package]
version = "0.0.2"

publish = false


[workspace.dependencies]
# Local library crates
brr = { path = "./crates/brr", version = "0.0.0" }
compiler = { path = "./crates/compiler", version = "0.0.0", features = [] }
shvc-sound-emu = { path = "./crates/shvc-sound-emu", version = "0.0.0" }

# Local binary crates
tad-compiler = { path = "./crates/tad-compiler", version = "0.0.0" }
wav2brr = { path = "./crates/wav2brr", version = "0.0.0" }

# External crates
clap = { version="4.3.3", features=[ "derive" ] }
serde = { version="1.0.164", features=[ "derive" ] }
serde_json = { version="1.0.97" }
relative-path = { version="1.9.0", features=[ "serde" ] }
sdl2 = { version="0.35.2", features=[] }
fltk = { version="1.4.12" }

cxx = { version="1.0.107" }

# External build dependencies
#
# Chose markdown as it has a security section in its readme file
# NOTE: Must use the alpha build.  This is a new crate that reuses an old name.
markdown = { version="1.0.0-alpha.14" }

regex = { version="1.10.2" }

cxx-build = { version="1.0.107" }


