[workspace]

members = [
    "crates/brr",
    "crates/wav2brr",
]


[workspace.dependencies]
# Local crates
brr = { path = "./crates/brr", version = "0.0.0" }
wav2brr = { path = "./crates/wav2brr", version = "0.0.0" }

# External crates
clap = { version="4.3.3", features=[ "derive" ] }


