[workspace]
resolver = "2"

members = [
    "crates/brr",
    "crates/compiler",

    "crates/tad-compiler",
    "crates/tad-gui",
    "crates/wav2brr",
]


[workspace.dependencies]
# Local library crates
brr = { path = "./crates/brr", version = "0.0.0" }
compiler = { path = "./crates/compiler", version = "0.0.0" }

# Local binary crates
tad-compiler = { path = "./crates/tad-compiler", version = "0.0.0" }
wav2brr = { path = "./crates/wav2brr", version = "0.0.0" }

# External crates
clap = { version="4.3.3", features=[ "derive" ] }
serde = { version="1.0.164", features=[ "derive" ] }
serde_json = { version="1.0.97" }

# Using git version to fix a segfault and panic involving non-parented widgets
# ::TODO switch to a non-git dependency when the next version of fltk-rs is released::
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }

