# cargo-deny configuration

[licenses]
version = 2

confidence-threshold = 0.93

allow = [
    "MIT",
    "ISC",
    "Zlib",
    "Apache-2.0",
    "Unicode-DFS-2016",
]


[bans]
multiple-versions = "deny"
wildcards = "deny"

deny = []

skip = [
    { name="bitflags", version = "1.3", reason = "used by sdl2" },
    { name="bitflags", version = "2.4", reason = "used by fltk" },

    { name="windows-sys", version="0.52.0", reason = "anstyle-query has not updated windows-sys" },
]


[advisories]
version = 2
yanked = "deny"


[sources]
unknown-registry = "deny"
unknown-git = "deny"


