[package]
# ::TODO either rename the project or change this crate name::
name = "tad-compiler"
description = "CLI app"
version = "0.0.0"
license = "MIT"

edition = "2021"


[dependencies]
# Local crates
compiler.workspace = true

# External crates
clap.workspace = true

