[package]
name = "tad-compiler"
description = "CLI app"
license = "MIT"

edition = "2021"

version = "0.0.0"
publish = false


[dependencies]
# Local crates
compiler.workspace = true

# External crates
clap.workspace = true

