[package]
name = "brr"
license = "MIT"

edition = "2021"
rust-version.workspace = true

publish = false

# This is a private internal crate.
# Using version "0.0.0" as I do not care about breaking changes.
version = "0.0.0"

