[package]
name = "wav2brr"
description = "A mono PCM wav to SNES brr encoder"
version = "0.0.0"
license = "MIT"

edition = "2021"

[dependencies]
# Local crates
brr.workspace = true

# External crates
clap.workspace = true

