[package]
name = "wav2brr"
description = "A mono PCM wav to SNES brr encoder"
license = "MIT"

edition = "2021"

version = "0.0.0"
publish = false


[dependencies]
# Local crates
brr.workspace = true

# External crates
clap.workspace = true

