---
name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '30 13 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      shell: bash
      run: |
        if [[ ${RUNNER_OS} == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y lib{sdl2,pango1.0,x11,xext,xft,xinerama,mpv}-dev\
                lib{xcursor,xrender,xfixes,webkit2gtk-4.1,vlc,png,gl1-mesa}-dev\
                ninja-build libglu1-mesa-dev
            git submodule update --init --recursive
            make -j -C wiz
            cargo fmt --check --all
            cargo clippy --quiet
            cargo test --quiet
            cargo build --quiet
        fi > /dev/null
