---
name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '30 13 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    steps:
    - name: Download deps
      shell: bash
      run: |
        if [[ ${RUNNER_OS} == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y lib{sdl2,pango1.0,x11,xext,xft,xinerama,mpv}-dev\
                lib{xcursor,xrender,xfixes,webkit2gtk-4.1,vlc,png,gl1-mesa}-dev\
                ninja-build libglu1-mesa-dev
        fi
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build app
      working-directory: "."
      shell: bash
      run: |
        if [[ ${RUNNER_OS} == "Linux" ]]; then
            git submodule update --init --recursive
            pushd wiz || return 1
            make -j8
            cargo clippy --quiet
        fi
